sudo: false

jobs:
  include:
    - stage: compile
      dist: bionic
      language: c
      addons:
        apt:
          packages:
            - cmake
            - gcc
            - libssl-dev
            - clang-format
      script:
        - ./configure
        - pushd build
        - make format -j$(nproc)
        - make -j$(nproc)
    - stage: tests
      dist: bionic
      language: c
      addons:
        apt:
          packages:
            - cmake
            - gcc
            - libssl-dev
            - ruby
      install:
        - gem install ceedling
      script:
        - ./configure
        - pushd build
        - make tests -j$(nproc)
    - stage: deploy
      if: branch = master
       branches:
         only:
           - master
       addons:
         apt:
           packages:
             - doxygen
       script:
         - doxygen Doxyfile
       deploy:
         provider: pages
         skip_cleanup: true
         local_dir: doc/html
         github_token: $GH_REPO_TOKEN
       on:
         branch: master
