sudo: false

jobs:
  include:
    - stage: compile
      dist: bionic
      language: c
      addons:
        apt:
          packages:
            - cmake
            - gcc
      script:
        - ./configure
        - pushd build
        - make format -j$(nproc)
    # - stage: deploy
    #   if: branch = master
    #   branches:
    #     only:
    #       - master
    #   addons:
    #     apt:
    #       packages:
    #         - doxygen
    #   script:
    #     - doxygen Doxyfile
    #   deploy:
    #     provider: pages
    #     skip_cleanup: true
    #     local_dir: docs
    #     github_token: $GH_REPO_TOKEN
    #     on:
    #       branch: master