sudo: false

jobs:
  include:
    - stage: compile
      dist: bionic
      language: c
      addons:
        apt:
          packages:
            - cmake
            - gcc
            - libssl-dev
            - clang-format
      script:
        - ./configure
        - pushd build
        - make format -j$(nproc)
        - make -j$(nproc)
    - stage: tests
      dist: bionic
      language: c
      addons:
        apt:
          packages:
            - cmake
            - gcc
            - libssl-dev
            - ruby
      install:
        - gem install ceedling
      script:
        - which ceedling
        - ./configure
        - pushd build
        - make tests -j$(nproc)