#ifndef WOLK_TYPES_H
#define WOLK_TYPES_H

#include "size_definitions.h"

#ifdef __cplusplus
extern "C" {
#endif

const char UNIT_NUMERIC[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_BOOLEAN[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_PERCENT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_DECIBEL[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_LOCATION[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_TEXT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_METRES_PER_SQUARE_SECOND[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_G[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_MOLE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_ATOM[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_RADIAN[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_REVOLUTION[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_DEGREE_ANGLE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_MINUTE_ANGLE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_SECOND_ANGLE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_CENTIRADIAN[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_GRADE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_SQUARE_METRE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_ARE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_HECTARE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_KATAL[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_BIT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_BYTE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_SECOND[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_MINUTE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_HOUR[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_DAY[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_WEEK[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_YEAR[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_MONTH[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_DAY_SIDEREAL[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_YEAR_SIDEREAL[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_YEAR_CALENDAR[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_POISE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_FARAD[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_COULOMB[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_E[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_FARADAY[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_FRANKLIN[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_SIEMENS[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_AMPERE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_GILBERT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_HENRY[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_VOLT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_CENTIVOLT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_MILLIVOLT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_OHM[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_JOULE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_ERG[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_ELECTRON_VOLT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_NEWTON[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_DYNE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_KILOGRAM_FORCE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_POUND_FORCE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_HERTZ[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_MEGAHERTZ[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_GIGAHERTZ[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_LUX[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_LAMBERT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_STOKE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_METRE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_KILOMETRE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_CENTIMETRE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_MILLIMETRE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_FOOT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_FOOT_SURVEY_US[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_YARD[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_INCH[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_MILE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_NAUTICAL_MILE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_ANGSTROM[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_ASTRONOMICAL_UNIT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_LIGHT_YEAR[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_PARSEC[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_POINT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_PIXEL[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_LUMEN[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_CANDELA[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_WEBER[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_MAXWELL[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_TESLA[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_GAUSS[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_KILOGRAM[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_GRAM[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_ATOMIC_MASS[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_ELECTRON_MASS[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_POUND[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_OUNCE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_TON_US[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_TON_UK[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_METRIC_TON[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_WATT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_HORSEPOWER[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_PASCAL[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_HECTOPASCAL[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_ATMOSPHERE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_BAR[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_MILLIBAR[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_MILLIMETER_OF_MERCURY[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_INCH_OF_MERCURY[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_GRAY[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_RAD[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_SIEVERT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_REM[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_BECQUEREL[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_CURIE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_RUTHERFORD[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_ROENTGEN[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_STERADIAN[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_SPHERE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_KELVIN[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_CELSIUS[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_RANKINE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_FAHRENHEIT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_METRES_PER_SECOND[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_MILES_PER_HOUR[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_KILOMETRES_PER_HOUR[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_KNOT[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_MACH[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_C[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_CUBIC_METRE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_LITRE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_DECILITRE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_MILLILITRE[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_CUBIC_INCH[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_GALLON_DRY_US[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_GALLON_UK[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_OUNCE_LIQUID_UK[MANIFEST_ITEM_UNIT_SIZE];
const char UNIT_UNKNOWN[MANIFEST_ITEM_UNIT_SIZE];

typedef enum {
    IN,
    IN_OUT,
} feed_type_t;

char* feed_type_to_string(feed_type_t feed_type);

const char** FEED_TYPE[MANIFEST_ITEM_FEED_TYPE_SIZE];

typedef enum { NUMERIC = 0, BOOLEAN, STRING, HEX, LOCATION, ENUM, VECTOR } data_type_t;

const char DATA_TYPE_STRING[MANIFEST_ITEM_DATA_TYPE_SIZE];
const char DATA_TYPE_NUMERIC[MANIFEST_ITEM_DATA_TYPE_SIZE];
const char DATA_TYPE_BOOLEAN[MANIFEST_ITEM_DATA_TYPE_SIZE];
const char DATA_TYPE_HEXADECIMAL[MANIFEST_ITEM_DATA_TYPE_SIZE];
const char DATA_TYPE_LOCATION[MANIFEST_ITEM_DATA_TYPE_SIZE];
const char DATA_TYPE_ENUM[MANIFEST_ITEM_DATA_TYPE_SIZE];
const char DATA_TYPE_VECTOR[MANIFEST_ITEM_DATA_TYPE_SIZE];

typedef enum {
    PUSH,
    PULL,
} outbound_mode_t;

const char PARAMETER_CONNECTIVITY_TYPE[PARAMETER_TYPE_SIZE];
const char PARAMETER_OUTBOUND_DATA_MODE[PARAMETER_TYPE_SIZE];
const char PARAMETER_OUTBOUND_DATA_RETENTION_TIME[PARAMETER_TYPE_SIZE];
const char PARAMETER_MAXIMUM_MESSAGE_SIZE[PARAMETER_TYPE_SIZE];
const char PARAMETER_FILE_TRANSFER_PLATFORM_ENABLED[PARAMETER_TYPE_SIZE];
const char PARAMETER_FILE_TRANSFER_URL_ENABLED[PARAMETER_TYPE_SIZE];
const char PARAMETER_FIRMWARE_UPDATE_ENABLED[PARAMETER_TYPE_SIZE];
const char PARAMETER_FIRMWARE_UPDATE_CHECK_TIME[PARAMETER_TYPE_SIZE];
const char PARAMETER_FIRMWARE_UPDATE_REPOSITORY[PARAMETER_TYPE_SIZE];
const char PARAMETER_FIRMWARE_VERSION[PARAMETER_TYPE_SIZE];
const char PARAMETER_GATEWAY[PARAMETER_TYPE_SIZE];
const char PARAMETER_GATEWAY_PARENT[PARAMETER_TYPE_SIZE];
const char PARAMETER_EXTERNAL_ID[PARAMETER_TYPE_SIZE];
const char PARAMETER_UNKNOWN[PARAMETER_TYPE_SIZE];


typedef enum {
    FILE_MANAGEMENT_STATE_FILE_TRANSFER,
    FILE_MANAGEMENT_STATE_FILE_READY,
    FILE_MANAGEMENT_STATE_ERROR,
    FILE_MANAGEMENT_STATE_ABORTED
} file_management_state_t;

typedef enum {
    FILE_MANAGEMENT_ERROR_NONE = -1,
    FILE_MANAGEMENT_ERROR_UNSPECIFIED = 0,
    FILE_MANAGEMENT_ERROR_TRANSFER_PROTOCOL_DISABLED = 1,
    FILE_MANAGEMENT_ERROR_UNSUPPORTED_FILE_SIZE = 2,
    FILE_MANAGEMENT_ERROR_MALFORMED_URL = 3,
    FILE_MANAGEMENT_ERROR_FILE_HASH_MISMATCH = 4,
    FILE_MANAGEMENT_ERROR_FILE_SYSTEM = 5,
    FILE_MANAGEMENT_ERROR_RETRY_COUNT_EXCEEDED = 10
} file_management_error_t;

typedef struct {
    file_management_state_t state;
    file_management_error_t error;
} file_management_status_t;

const char* file_management_status_as_str(file_management_status_t* status);

#ifdef __cplusplus
}
#endif

#endif // WOLK_TYPES_H
